# Generated by Django 5.0.4 on 2024-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Discreption', models.CharField(blank=True, max_length=100, null=True)),
                ('Category_image', models.ImageField(blank=True, null=True, upload_to='product images')),
            ],
        ),
    ]
