# Generated by Django 5.0.4 on 2024-05-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_category_db_delete_shop_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('pro_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_image', models.ImageField(blank=True, null=True, upload_to='category images')),
            ],
        ),
    ]
