# Generated by Django 5.0.4 on 2024-05-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdb',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
