# Generated by Django 5.0.4 on 2024-05-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_contactdb_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Password', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Profileimage', models.ImageField(blank=True, null=True, upload_to='category images')),
            ],
        ),
    ]
