# Generated by Django 5.0.4 on 2024-05-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_signup_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_db',
            name='Confirm_Password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
