# Generated by Django 5.0.4 on 2024-06-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_checkoutdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
